### ISSUE TITLE
Use atom modules inside Meteor

### ISSUE THREAD

**Issue by hell000** [sircharleswatson/Electrometeor#10]
So far Electrometeor is working fine for me on mac. I will test it on win soon too. 

How would you use atom modules inside meteor?
Eg. require('shell').openExternal(url); to open a link using the default browser

ps: I'm new to node, so might be missing something.

**Comment by flaviocopes** [comment]
Hi @hell000 they work fine for me by just putting them in the Meteor `client` code (e.g. inside Meteor.isClient)

**Comment by hell000** [comment]
@flaviocopes thanks! Dumb mistake. I had turned off node in the BrowserWindow because of some other issue so require wasn't working.
