### ISSUE TITLE
windows support, when?

### ISSUE THREAD

**Issue by yuomtheara** [sircharleswatson/Electrometeor#2]
Now i base on windows 7.
have any plan to support on windows,???

**Comment by sircharleswatson** [comment]
Hey @yuomtheara !

I will try to get that out by Friday. I'll be working on it some more this week.

**Comment by skolade** [comment]
@sircharleswatson Thanks for your hardwork adn sharing it with the Meteor community! Looking forward to digging into the code deeper! Question what is the timeline for shelljs? I am going to deep into shelljs!

**Comment by sircharleswatson** [comment]
@skolade Actually, I was about to start working on that right now :)

**Comment by skolade** [comment]
@sircharleswatson sweet I notice a few minute ago about the fun you are having on your twitter post!

**Comment by sircharleswatson** [comment]
Wasn't able to get it done by Friday. But if you check out the "shelljs-scripts" branch, there is a lot of progress there. It now runs on Windows, Mac, and Linux. However, It still only builds for distribution on Mac. But I'm close to having the other platforms ready for building. 

This week however, I'll be taking a break from programming to prepare for my trip to Prague next Friday. So the windows and Linux  builds will most likely be ready sometime around the end of the month. :) Thanks for being patient guys :)

**Comment by sircharleswatson** [comment]
Windows support now available! Check [v0.2.0](https://github.com/sircharleswatson/Electrometeor/tree/v0.2.0)!

**Comment by yuomtheara** [comment]
Look great, I will test.
