### ISSUE TITLE
what are the py2.7 and other dependencies needed for for windows?

### ISSUE THREAD

**Issue by dpastoor** [sircharleswatson/Electrometeor#9]
Is there a way to reduce those dependencies?

**Comment by dpastoor** [comment]
ah looks like all that is necessary to build the npm packages on windows so won't be able to reduce that dependency ever :-/ http://www.steveworkman.com/node-js/2012/installing-jsdom-on-windows/

**Comment by sircharleswatson** [comment]
@dpastoor Ya! It has to do with the way Fibers is built with node-gyp. Among other things. I am a Mac guy so when I was working on the windows version I was saddened by how much of a pain deeloping on Windows is :disappointed:

**Comment by dpastoor** [comment]
Yep - I feel you! I personally have gotten into personally using my mac for development, but the rest of my team and most of the industry is on windows so if I want to develop something for other people to use gotta roll with the punches.

At least meteor on windows surprisingly clean, I've been really happy running (little baby apps on localhost) between my mac and windows PC's, but it'd be nice to actually be able to bundle things up into a distributable
